### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by settala1**
i have made changes to existing word document for contributing to AirQo-hardware Repo FEB/2023 which was assigned to me and @marvin changes made were creating doc based on descending order of date events . i hope you will appreciate the changes.

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @settala1 , this is good. I will review the changes asap. Appears I cant view the file fro my phone. 😀

**Comment by settala1** [comment]
Thanks Martin
I guess it's in bin format but u can view it after downloading it

**Review by Baalmart — COMMENTED** [review]
Thanks @settala1  , this looks good to me. Just have a few observations to share...

Firstly, I am not very sure if this document should be in our Github repository. Aren't these just meeting minutes? Putting them in Github might bring about unnecessary complexity when it comes to making changes/updates after every meeting.

Could we review our naming convention for all files and directories. Naming conventions for Github repositories are important for clarity and consistency. Here are some considerations and guidelines to follow:

- Use lowercase letters: Github is case-sensitive, so using all lowercase letters can prevent confusion.
- Use hyphens for spaces: When naming a repository, it's important to use a consistent separator for spaces. Hyphens (-) are commonly used, while underscores (_) or spaces are not recommended.
- Be descriptive: The name of the repository should give a clear indication of its purpose or contents. It's important to choose a name that is descriptive, concise, and memorable.
- Keep it short: Avoid using long names or abbreviations that may be confusing to users. A shorter name is often easier to remember and type.
- Avoid special characters: Special characters such as !, @, #, $, %, &, *, etc. should be avoided in the name of the repository. These characters can cause issues with some programming languages or tools.
- Use consistent naming conventions: If you have multiple repositories, it's important to use a consistent naming convention to make them easy to find and organize. You can use prefixes or suffixes to differentiate between related repositories.

Example:

- docs/contributing-to-airqo-hardware-repo-2023.docx

The above examples are just emphasizing the need to keep names without spaces in names, also keeping things in respective folders -- as you notice, that uploded document could have been put inside the docs directory.

Thanks again!

**Comment by settala1** [comment]
thanks martin, noted with thanks
I was cationed with anold so that's why i made my PR
Regards,
Settala George William
Embedded Systems and Network Support
Mobile Number: +256 701 379 716

**Pull request closed without merging**
