### PR TITLE
 added some information on the README file, to include sytling and li…

### PR DESCRIPTION
**Pull request by deogratius2phantom**
…nks, work in progress

### CODE REVIEW

**Comment by deogratius2phantom** [comment]
hello all, please take a look at the readme file, styling is only available aftter a PR is merged, luckily ive tested  this in my own fork of the hardware repo her is a [link](https://github.com/deogratius2phantom/AirQo-hardware/blob/staging/README.md) to see how it will look, to inspire you to merge my PR...hahahah

**Comment by deogratius2phantom** [comment]
Reviewers...🥸

**Review by Baalmart — APPROVED** [review]
This looks good to me. Thanks @deogratius2phantom

**Review by settala1 — COMMENTED** [review]
@deogratius2phantom Great work
if its arrangemant i thought 
1. cad tools
2. block diagram
3. hardware design
4. sensors pick to use
5. Firmware design
6. Firmware code
7. developed with cpp and arduino framework.
Thats my thought i maybe wrong.

**Review by settala1 — APPROVED** [review]
thanks @deogratius2phantom it's great work

**Pull request merged**
