### PR TITLE
Added folders for file organisation

### PR DESCRIPTION
**Pull request by NsubugaAnold**
The folders are organised in a way to depict the possible codes based on relationship.

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @NsubugaAnold , this looks good to me. Just have a few observations to share...

Could we review our naming convention for all files and directories. Naming conventions for Github repositories are important for clarity and consistency. Here are some considerations and guidelines to follow:

- Use lowercase letters: Github is case-sensitive, so using all lowercase letters can prevent confusion.
- Use hyphens for spaces: When naming a repository, it's important to use a consistent separator for spaces. Hyphens (-) are commonly used, while underscores (_) or spaces are not recommended.
- Be descriptive: The name of the repository should give a clear indication of its purpose or contents. It's important to choose a name that is descriptive, concise, and memorable.
- Keep it short: Avoid using long names or abbreviations that may be confusing to users. A shorter name is often easier to remember and type.
- Avoid special characters: Special characters such as !, @, #, $, %, &, *, etc. should be avoided in the name of the repository. These characters can cause issues with some programming languages or tools.
- Use consistent naming conventions: If you have multiple repositories, it's important to use a consistent naming convention to make them easy to find and organize. You can use prefixes or suffixes to differentiate between related repositories.

Example:

- power-management
- operations
- sensors
- data
- firmware

The above examples are just emphasizing the need to keep things `lowercase`.

**Review by deogratius2phantom — COMMENTED** [review]
is it possible to use .cpp files

**Comment by settala1** [comment]
looks good but i thought the extensions like .cpp, and .h last time we said were not needed @NsubugaAnold 
i still see them there.

**Review by settala1 — COMMENTED** [review]
looks good but i thought the extensions like .cpp, and .h last time we said were not needed @NsubugaAnold
i still see them there.

**Review by semajoel — CHANGES_REQUESTED** [review]
image
 Hi Anold see the pic for adjustments

**Comment by BandaMarvin-cpu** [comment]
Good stuff over here

**Pull request closed without merging**
