### PR TITLE
a reorganization of the folder structure to easily guide development …

### PR DESCRIPTION
**Pull request by deogratius2phantom**
ive broken down the folders to easily create projects. hardware department has work around firmware and hardware design

### CODE REVIEW

**Review by deogratius2phantom — COMMENTED** [review]
ive started the review process here, please suggest ideas

**Review by Baalmart — COMMENTED** [review]
Thanks @deogratius2phantom for this PR.

For the folder names, I would suggest something shorter and also lower case in nature: for example:

1. **firmware**
      1.1 module-one
      1.1 module-two
      1.3 module-three
2. **hardware**
      2.1 casing
      2.2 etc

**Review by 123MwanjeMike — COMMENTED** [review]
Thank you @deogratius2phantom 
The files changed look good to me.
I however do share the same opinion on the module names as @Baalmart has shared

**Comment by settala1** [comment]
Hi Okedi, could u flow the firmware structure like 
* AirQo-GrevC10_Good
* Battery
* clocking
* communication
* DeltaT
* EEPROMSettings
* firebase
* FOTA
* Gen5RevCJson
* SD-Storage
* temp-Humidity

**Comment by settala1** [comment]
@deogratius2phantom if the firmware is still in the testing phase 
The file folder should be named Test file or Test code version ......
if we have certained that the firmware is fully functional the it should be named Firmware Pro standing for production phase

**Comment by wabinyai** [comment]
The name, have we considered if we are 10 years away from today. The numbering

**Review by settala1 — COMMENTED** [review]
the organization structure is well layered out

**Review by wabinyai — APPROVED** [review]
All is good then.

**Comment by wabinyai** [comment]
All is good then.

**Comment by deogratius2phantom** [comment]
merging the PR with accepted folder structure for embedded systems development

**Pull request merged**
